// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9wzZb750WNBp-JOotPw2YFQ7Aa-fCZU4',
    appId: '1:955275944362:web:16c4543dfb1db9cf0acbd3',
    messagingSenderId: '955275944362',
    projectId: 'clasificador-figuras',
    authDomain: 'clasificador-figuras.firebaseapp.com',
    storageBucket: 'clasificador-figuras.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBuQT_4SWhK41DiY-d543VdU0WHurcIeY',
    appId: '1:955275944362:android:0c9c366c0031a72e0acbd3',
    messagingSenderId: '955275944362',
    projectId: 'clasificador-figuras',
    storageBucket: 'clasificador-figuras.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw3X03tGalvC1aLnvAX5BE0zkfJv04TH8',
    appId: '1:955275944362:ios:2709c5ef0470f52e0acbd3',
    messagingSenderId: '955275944362',
    projectId: 'clasificador-figuras',
    storageBucket: 'clasificador-figuras.appspot.com',
    iosClientId: '955275944362-4dofe4ucg39jva4p26bsii96sbn979jb.apps.googleusercontent.com',
    iosBundleId: 'com.example.iaProyectorn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw3X03tGalvC1aLnvAX5BE0zkfJv04TH8',
    appId: '1:955275944362:ios:2709c5ef0470f52e0acbd3',
    messagingSenderId: '955275944362',
    projectId: 'clasificador-figuras',
    storageBucket: 'clasificador-figuras.appspot.com',
    iosClientId: '955275944362-4dofe4ucg39jva4p26bsii96sbn979jb.apps.googleusercontent.com',
    iosBundleId: 'com.example.iaProyectorn',
  );
}
